server:
  port: 9090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ivandiassantos/prova-configuracoes-gerais
          #proxy:
          #  https:
          #    host: localhost
          #    password: 18018080
          #    port: '40080'
          #    username: C1298479